version: '3'
services:
  webserver:
    image: php:8.0-apache
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
